[package]
edition = "2018"
name = "macro-attr-2018"
version = "0.4.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "This crate provides the `macro_attr!` macro that enables the use of custom, macro-based attributes and derivations."
readme = "README.md"
documentation = "https://docs.rs/crate/macro-attr-2018/"
keywords = ["custom", "derive", "attribute", "macro"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/macro-attr-2018"

[workspace]
members = [
    "tests/derive-name-macro",
    "tests/derive-name-proc",
    "tests/derive-name-test",
]

[dev-dependencies]
enum_derive = { version = "0.1.7", default-features = false }
rustc-serialize = "0.3.15"
