[package]
name = "macro-attr-2018"
version = "0.2.1"
authors = ["Warlock <internalmike@gmail.com>"]

description = "This crate provides the `macro_attr!` macro that enables the use of custom, macro-based attributes and derivations.  Supercedes the `custom_derive` crate."
repository = "https://github.com/A1-Triard/macro-attr-2018"
documentation = "https://docs.rs/crate/macro-attr-2018/"
license = "MIT OR Apache-2.0"
keywords = ["custom", "derive", "attribute", "macro"]

exclude = [
    "local/*",
    "doc-pkg/*",
    "scripts/*",
    "update-docs.py",
]

[workspace]
members = [
    "tests/derive-name-macro",
    "tests/derive-name-proc",
    "tests/derive-name-test",
]

[features]
default = ["std"]
std = []

[dev-dependencies]
rustc-serialize = "0.3.15"
