[package]
edition = "2021"
name = "ensure_no_std"
version = "0.0.0"
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
educe = "0.4.19"
exit-no-std = "0.2.0"
macro-attr-2018 = { path = ".." }
