[package]
name = "newtype_derive"
version = "0.1.3"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

description = "This crate provides macros for deriving common traits for newtype structures."
repository = "https://github.com/DanielKeep/rust-custom-derive"
documentation = "https://danielkeep.github.io/rust-custom-derive/doc/newtype_derive/index.html"
license = "MIT"
keywords = ["newtype", "derive", "wrapper", "custom_derive", "macro"]

[dev-dependencies]
custom_derive = "0.1.1"
